apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/instance: mastodon
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mastodon
    app.kubernetes.io/version: v4.0.2
    helm.sh/chart: mastodon-4.0.0
  name: mastodon-media-remove
  namespace: mastodon
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          name: mastodon-media-remove
        spec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/part-of
                        operator: In
                        values:
                          - rails
                  topologyKey: kubernetes.io/hostname
          containers:
            - command:
                - bin/tootctl
                - media
                - remove
              env:
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: mastodon-postgresql
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: redis-password
                      name: mastodon-redis
                - name: PORT
                  value: '3000'
              envFrom:
                - configMapRef:
                    name: mastodon-env
                - secretRef:
                    name: mastodon
              image: 'tootsuite/mastodon:v4.0.2'
              imagePullPolicy: IfNotPresent
              name: mastodon-media-remove
              volumeMounts:
                - mountPath: /opt/mastodon/public/assets
                  name: assets
                - mountPath: /opt/mastodon/public/system
                  name: system
          restartPolicy: OnFailure
          volumes:
            - name: assets
              persistentVolumeClaim:
                claimName: mastodon-assets
            - name: system
              persistentVolumeClaim:
                claimName: mastodon-system
  schedule: 0 0 * * 0
