apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-docker
  namespace: civic-tech-taxonomy
spec:
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: mysql.civic-tech-taxonomy.svc.cluster.local
            - name: DB_USER
              value: root
            - name: DB_PWD
              value: JNVdnoK8PvWG6qrjh1UAnMClMsQrJSIk
            - name: DB_DB
              value: cfa_project_index
          image: 'ghcr.io/codeforamerica/civic-tech-taxonomy/api-server:2585049'
          name: api-server
          ports:
            - containerPort: 8081
              name: http
