apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: mastodon
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mastodon
    app.kubernetes.io/version: v4.0.2
    helm.sh/chart: mastodon-4.0.0
  name: mastodon-streaming
  namespace: mastodon
spec:
  ports:
    - name: streaming
      port: 4000
      protocol: TCP
      targetPort: streaming
  selector:
    app.kubernetes.io/component: streaming
    app.kubernetes.io/instance: mastodon
    app.kubernetes.io/name: mastodon
  type: ClusterIP
