apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: mastodon
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mastodon
    app.kubernetes.io/version: v4.0.2
    helm.sh/chart: mastodon-4.0.0
  name: mastodon-web
  namespace: mastodon
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: mastodon
    app.kubernetes.io/name: mastodon
  type: ClusterIP
