apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app.kubernetes.io/component: coordinating-only
    app.kubernetes.io/instance: mastodon
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: elasticsearch
    helm.sh/chart: elasticsearch-19.0.1
  name: mastodon-elasticsearch
  namespace: mastodon
spec:
  ports:
    - name: tcp-rest-api
      nodePort: null
      port: 9200
      targetPort: rest-api
    - name: tcp-transport
      nodePort: null
      port: 9300
  selector:
    app.kubernetes.io/component: coordinating-only
    app.kubernetes.io/instance: mastodon
    app.kubernetes.io/name: elasticsearch
  sessionAffinity: None
  type: ClusterIP
