apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: sidekiq-all-queues
    app.kubernetes.io/instance: mastodon
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mastodon
    app.kubernetes.io/part-of: rails
    app.kubernetes.io/version: v4.0.2
    helm.sh/chart: mastodon-4.0.0
  name: mastodon-sidekiq-all-queues
  namespace: mastodon
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: sidekiq-all-queues
      app.kubernetes.io/instance: mastodon
      app.kubernetes.io/name: mastodon
      app.kubernetes.io/part-of: rails
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config-configmap: ae9887455a348ef80cecda8f4f1f3dd94687b3a6360e31b1cd4b25fae27e484c
        checksum/config-secrets: 403073b37391e4b68018b3394831baef7a9300bae4b4ec8c1ee6fbeac5fb7b2b
        rollme: '1'
      labels:
        app.kubernetes.io/component: sidekiq-all-queues
        app.kubernetes.io/instance: mastodon
        app.kubernetes.io/name: mastodon
        app.kubernetes.io/part-of: rails
    spec:
      containers:
        - command:
            - bundle
            - exec
            - sidekiq
            - '-c'
            - '25'
            - '-q'
            - 'default,8'
            - '-q'
            - 'push,6'
            - '-q'
            - 'ingress,4'
            - '-q'
            - 'mailers,2'
            - '-q'
            - pull
            - '-q'
            - scheduler
          env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mastodon-postgresql
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: mastodon-redis
          envFrom:
            - configMapRef:
                name: mastodon-env
            - secretRef:
                name: mastodon
          image: 'tootsuite/mastodon:v4.0.2'
          imagePullPolicy: IfNotPresent
          name: mastodon
          resources: {}
          securityContext: {}
          volumeMounts:
            - mountPath: /opt/mastodon/public/assets
              name: assets
            - mountPath: /opt/mastodon/public/system
              name: system
      securityContext:
        fsGroup: 991
        runAsGroup: 991
        runAsUser: 991
      serviceAccountName: mastodon
      volumes:
        - name: assets
          persistentVolumeClaim:
            claimName: mastodon-assets
        - name: system
          persistentVolumeClaim:
            claimName: mastodon-system
