apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: mastodon
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mastodon
    app.kubernetes.io/version: v4.0.2
    helm.sh/chart: mastodon-4.0.0
  name: mastodon-web
  namespace: mastodon
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: web
      app.kubernetes.io/instance: mastodon
      app.kubernetes.io/name: mastodon
      app.kubernetes.io/part-of: rails
  template:
    metadata:
      annotations:
        checksum/config-configmap: c1fab835e890923e63a73ef6d925bf2e9c9feae3d5baf7d74de00546022f7561
        checksum/config-secrets: 403073b37391e4b68018b3394831baef7a9300bae4b4ec8c1ee6fbeac5fb7b2b
        rollme: '1'
      labels:
        app.kubernetes.io/component: web
        app.kubernetes.io/instance: mastodon
        app.kubernetes.io/name: mastodon
        app.kubernetes.io/part-of: rails
    spec:
      containers:
        - command:
            - bundle
            - exec
            - puma
            - '-C'
            - config/puma.rb
          env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mastodon-postgresql
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: mastodon-redis
            - name: PORT
              value: '3000'
          envFrom:
            - configMapRef:
                name: mastodon-env
            - secretRef:
                name: mastodon
          image: 'tootsuite/mastodon:v4.0.2'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            tcpSocket:
              port: http
          name: mastodon-web
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: http
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /health
              port: http
            periodSeconds: 5
          volumeMounts:
            - mountPath: /opt/mastodon/public/assets
              name: assets
            - mountPath: /opt/mastodon/public/system
              name: system
      securityContext:
        fsGroup: 991
        runAsGroup: 991
        runAsUser: 991
      serviceAccountName: mastodon
      volumes:
        - name: assets
          persistentVolumeClaim:
            claimName: mastodon-assets
        - name: system
          persistentVolumeClaim:
            claimName: mastodon-system
