apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 7.3.5
    helm.sh/chart: grafana-6.2.1
  name: grafana
  namespace: grafana
spec:
  rules:
    - host: metrics.sandbox.k8s.brigade.cloud
      http:
        paths:
          - backend:
              serviceName: grafana
              servicePort: 80
            path: /
  tls:
    - hosts:
        - metrics.sandbox.k8s.brigade.cloud
      secretName: grafana-tls
