apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
  namespace: civic-tech-taxonomy

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin
  namespace: civic-tech-taxonomy
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods/exec", "pods/portforward"]
  verbs: ["create"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin
  namespace: civic-tech-taxonomy
subjects:
- kind: ServiceAccount
  name: admin
  namespace: civic-tech-taxonomy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
