kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: api-server
  namespace: civic-tech-taxonomy
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - api.taxonomy.sandbox.k8s.brigade.cloud
      secretName: api-server-tls
  rules:
    - host: api.taxonomy.sandbox.k8s.brigade.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-server
                port:
                  number: 80
