apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: portforwarder
  namespace: civic-tech-taxonomy
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - ''
    resources:
      - pods/portforward
    verbs:
      - create
