apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: civic-tech-taxonomy
spec:
  selector:
    matchLabels:
      service: mysql
  serviceName: mysql
  template:
    metadata:
      labels:
        service: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: JNVdnoK8PvWG6qrjh1UAnMClMsQrJSIk
          image: 'mysql:5.6'
          name: mysql
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data
  updateStrategy:
    type: Recreate
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
