apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: 'before-hook-creation,hook-succeeded'
    helm.sh/hook-weight: '-2'
  labels:
    app.kubernetes.io/instance: mastodon
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mastodon
    app.kubernetes.io/version: v4.0.2
    helm.sh/chart: mastodon-4.0.0
  name: mastodon-assets-precompile
  namespace: mastodon
spec:
  template:
    metadata:
      name: mastodon-assets-precompile
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/part-of
                    operator: In
                    values:
                      - rails
              topologyKey: kubernetes.io/hostname
      containers:
        - command:
            - bash
            - '-c'
            - |
              bundle exec rake assets:precompile && yarn cache clean
          env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mastodon-postgresql
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: mastodon-redis
            - name: PORT
              value: '3000'
          envFrom:
            - configMapRef:
                name: mastodon-env
            - secretRef:
                name: mastodon
          image: 'tootsuite/mastodon:v4.0.2'
          imagePullPolicy: IfNotPresent
          name: mastodon-assets-precompile
          volumeMounts:
            - mountPath: /opt/mastodon/public/assets
              name: assets
            - mountPath: /opt/mastodon/public/system
              name: system
      restartPolicy: Never
      volumes:
        - name: assets
          persistentVolumeClaim:
            claimName: mastodon-assets
        - name: system
          persistentVolumeClaim:
            claimName: mastodon-system
